/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtonsExample: typeof import('./components/examples/ActionButtonsExample.vue')['default']
    AppFooter: typeof import('./components/layouts/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/layouts/AppNavbar.vue')['default']
    AppSidebar: typeof import('./components/layouts/AppSidebar.vue')['default']
    PermissionButton: typeof import('./components/common/PermissionButton.vue')['default']
    PermissionWrapper: typeof import('./components/common/PermissionWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInitialsAvatar: typeof import('./components/layouts/UserInitialsAvatar.vue')['default']
  }
}
