/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AccessControlPlaceholder': RouteRecordInfo<'/AccessControlPlaceholder', '/AccessControlPlaceholder', Record<never, never>, Record<never, never>>,
    '/ActivityLogPlaceholder': RouteRecordInfo<'/ActivityLogPlaceholder', '/ActivityLogPlaceholder', Record<never, never>, Record<never, never>>,
    '/documents/': RouteRecordInfo<'/documents/', '/documents', Record<never, never>, Record<never, never>>,
    '/documents/[id]': RouteRecordInfo<'/documents/[id]', '/documents/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/documents/[id]/edit': RouteRecordInfo<'/documents/[id]/edit', '/documents/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/documents/create': RouteRecordInfo<'/documents/create', '/documents/create', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/NotFoundPlaceholder': RouteRecordInfo<'/NotFoundPlaceholder', '/NotFoundPlaceholder', Record<never, never>, Record<never, never>>,
    '/search-documents': RouteRecordInfo<'/search-documents', '/search-documents', Record<never, never>, Record<never, never>>,
    '/SearchDocumentsPlaceholder': RouteRecordInfo<'/SearchDocumentsPlaceholder', '/SearchDocumentsPlaceholder', Record<never, never>, Record<never, never>>,
    '/UnauthorizedPlaceholder': RouteRecordInfo<'/UnauthorizedPlaceholder', '/UnauthorizedPlaceholder', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[id]/edit': RouteRecordInfo<'/users/[id]/edit', '/users/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/create': RouteRecordInfo<'/users/create', '/users/create', Record<never, never>, Record<never, never>>,
  }
}
